name: ESP Build

on:
  push:

jobs:
  test_builds:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-platform:
          - nodemcuv2
          - esp32

    steps:
      - name: Select Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install PlatformIO
        run: |
          pip install -U https://github.com/platformio/platformio-core/archive/master.zip
          platformio update
          
      - name: Check out the Release
        uses: actions/checkout@v2

      - name: Run PlatformIO for ${{ matrix.test-platform }}
        run: platformio run -e ${{ matrix.test-platform }}

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.test-platform }}
          path: .pio/build/${{ matrix.test-platform }}/firmware.bin  
